### ISSUE TITLE
(in devtools tab): "Cannot find imported React library"

### ISSUE THREAD

**Issue by crazy4groovy** [React-Sight/React-Sight#90]
chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:136 Uncaught RangeError: Maximum call stack size exceeded
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:136)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:164)

**Comment by gpbl** [comment]
Somewhat related: https://github.com/React-Sight/React-Sight/issues/85

**Comment by mricketts** [comment]
I'm getting the same error with my react app.

**Comment by ido-ofir** [comment]
Same here..

**Comment by ifflanb** [comment]
Same here

**Comment by trevtrich** [comment]
Same for me.

**Comment by reemyrail** [comment]
Same for me

**Comment by ghost** [comment]
same here

**Comment by ekros** [comment]
Tested with my projects and some react-powered websites. I'm getting the same error over and over again.

**Comment by durul** [comment]
Same for me

**Comment by bionicvapourboy** [comment]
Same for me from react 16.x

**Comment by alistaircolling** [comment]
I'm getting this error on React `15.4.2` :/

![image](https://user-images.githubusercontent.com/111540/33935021-6735da22-dff2-11e7-851f-3a7152fe9821.png)

```

installHook.js:180 Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at parseFunction (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:180:24)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:155:28)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
    at parseProps (chrome-extension://aalppolilappfakpmdfdkpppdnhpgifn/backend/installHook.js:166:30)
```
